"""empty message

Revision ID: 3eb447cc330e
Revises: 
Create Date: 2022-07-03 21:56:04.724267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb447cc330e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.String(length=30), nullable=False),
    sa.Column('superhero', sa.String(length=50), nullable=False),
    sa.Column('alter_ego', sa.String(length=30), nullable=False),
    sa.Column('first_appearance', sa.String(length=100), nullable=False),
    sa.Column('character', sa.String(length=400), nullable=False),
    sa.Column('publisher', sa.String(length=90), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heroes')
    # ### end Alembic commands ###
